"""empty message

Revision ID: 56f03fddba96
Revises: ecf3d026d0a2
Create Date: 2020-12-10 11:08:04.792078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f03fddba96'
down_revision = 'ecf3d026d0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'artist_id')
    # ### end Alembic commands ###
