"""empty message

Revision ID: 939847db4d02
Revises: 
Create Date: 2020-12-09 21:45:45.965744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939847db4d02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'num_upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('num_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
